version: '3.7'
services:
  node-app:
    build: artifacts/gate-simulator
    image: node-app:1.0
    container_name: node
    ports:
      - '9999:9999'
  mysql:
    image: mysql:8.0.18
    command:
      --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - '3306:3306'
    volumes:
    - ./data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass




