version: '3.7'
services:
  node-app:
    build: artifacts/gate-simulator
    image: node-app:1.0
    container_name: node-app
    ports:
      - '9999:9999'
  postgres:
    image: postgres:12-alpine
    container_name: postgresql
    ports:
        - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/pgdata
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=app
      - POSTGRES_DB=app




